### ISSUE TITLE
XMLHttpRequest is not defined when running under node

### ISSUE THREAD

**Issue by chao-master** [LionRoar/youtube-api-v3-search#2]
While running the latest version on node the follow error occurs:
```
ReferenceError: XMLHttpRequest is not defined
    at e.exports (.../node_modules/youtube-api-v3-search/dist/youtube-api-v3-search.min.js:1:940)
    at e.exports (.../node_modules/youtube-api-v3-search/dist/youtube-api-v3-search.min.js:1:1560)
    at e.exports (.../node_modules/youtube-api-v3-search/dist/youtube-api-v3-search.min.js:1:870)
```
It would appear that the browser version is trying to be used instead of the node version.
The issue doesn't occur on version 1.1.0, but I am not sure which version brakes it

**Comment by LionRoar** [comment]
Thank you ! it was an entry point error in ` package.json`  it's fixed now in version 1.1.5 :)
