### ISSUE TITLE
Getting Error: socket hang up and it does not pass as error

### ISSUE THREAD

**Issue by ghost** [LionRoar/youtube-api-v3-search#4]
More often than not, I get this error:
`Error: socket hang up
^

SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at ClientRequest.https.get.on (/home/user/project/node_modules/youtube-api-v3-search/src/request/node-request.js:15:22)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`
It locks up the entire program until I close it. Is there any reason for this? Am I missing something? Any help would be appreciated.
The options I'm passing: 
`let options = {
    q:search,
    part:'snippet',
    type:'video',
    maxResults:5
}`

**Comment by LionRoar** [comment]
check that all the options values are in string
